# Storing Data: Files and HDF5


Create a subdirectory to store the data files for this lecture.

In [1]:
!mkdir -p storing_data

Create some sample data.

In [2]:
import numpy as np

In [100]:
np.random.seed(6950)
A = np.random.randint(0, 1024, size=(50, 50), dtype='uint16')
np.savetxt('storing_data/matrix.txt', A, fmt='%d', delimiter=',')

## Files in Python

#### Reading from a text file:

In [101]:
f = open('storing_data/matrix.txt')
matrix = []
for line in f.readlines():
    row = [int(x) for x in line.split(',')]
    matrix.append(row)
f.close() # Files should always be closed!

In [102]:
matrix[:3]

[[152,
  312,
  1004,
  578,
  42,
  158,
  528,
  970,
  367,
  783,
  704,
  783,
  288,
  215,
  913,
  873,
  914,
  745,
  282,
  928,
  607,
  745,
  265,
  269,
  981,
  174,
  84,
  688,
  694,
  904,
  567,
  824,
  487,
  736,
  825,
  485,
  188,
  139,
  541,
  523,
  600,
  208,
  449,
  752,
  382,
  665,
  962,
  922,
  184,
  890],
 [738,
  802,
  444,
  1022,
  214,
  50,
  820,
  22,
  372,
  531,
  869,
  553,
  616,
  117,
  232,
  1004,
  549,
  366,
  497,
  448,
  319,
  206,
  912,
  73,
  304,
  816,
  173,
  295,
  739,
  947,
  980,
  635,
  814,
  768,
  980,
  471,
  943,
  720,
  386,
  715,
  976,
  828,
  776,
  962,
  42,
  6,
  583,
  904,
  373,
  561],
 [156,
  115,
  463,
  551,
  810,
  132,
  83,
  418,
  170,
  736,
  319,
  651,
  205,
  321,
  243,
  643,
  856,
  994,
  724,
  230,
  983,
  592,
  598,
  12,
  1022,
  721,
  69,
  291,
  930,
  1009,
  853,
  977,
  819,
  362,
  914,
  741,
  607,
  801,
  995,
  942,
  428,
  226,
  717,
  4

In [103]:
A = np.array(matrix)
A

array([[ 152,  312, 1004, ...,  922,  184,  890],
       [ 738,  802,  444, ...,  904,  373,  561],
       [ 156,  115,  463, ...,  151,  438,  730],
       ...,
       [ 884,  712,  923, ...,  988,  387,  136],
       [ 610,  967,  917, ...,  227,  383,  482],
       [ 295,  901,  355, ...,  999,  220,  726]])

#### Writing to a file:

In [104]:
f = open('storing_data/matrix_2.txt', 'w')
for row in matrix:
    line = ",".join([ str(x) for x in row ])
    f.write(line + '\n')
f.close()

#### Useful file modes:

 | Mode | Description                                                    |  
 |:----:| :------------------------------------------------------------- |
 | 'r'  | Open a file for **reading** (read only).                       |
 | 'w'  | Open a file for **writing** (current content will be deleted!).|
 | 'a'  | Open a file for **appending** (writing after current content). |
 | '+'  | **Update** (open file for both reading and writing).           |



#### Updating a text file:

In [105]:
!cat storing_data/matrix_2.txt

152,312,1004,578,42,158,528,970,367,783,704,783,288,215,913,873,914,745,282,928,607,745,265,269,981,174,84,688,694,904,567,824,487,736,825,485,188,139,541,523,600,208,449,752,382,665,962,922,184,890
738,802,444,1022,214,50,820,22,372,531,869,553,616,117,232,1004,549,366,497,448,319,206,912,73,304,816,173,295,739,947,980,635,814,768,980,471,943,720,386,715,976,828,776,962,42,6,583,904,373,561
156,115,463,551,810,132,83,418,170,736,319,651,205,321,243,643,856,994,724,230,983,592,598,12,1022,721,69,291,930,1009,853,977,819,362,914,741,607,801,995,942,428,226,717,484,492,551,37,151,438,730
657,148,444,25,731,648,295,890,965,48,758,2,625,682,859,448,427,744,1009,787,608,202,777,440,597,650,309,443,760,123,222,848,693,150,720,410,34,86,123,624,134,320,159,859,254,733,626,599,271,876
752,917,925,844,718,530,354,334,723,774,1000,777,438,465,344,377,196,211,159,341,895,425,999,312,251,456,721,140,100,995,447,551,542,518,394,578,442,265,296,552,67,54,1020,747,968,15,221,796,633,921
800,142,35,39

In [106]:
f = open('storing_data/matrix_2.txt', 'r+')
orig = f.read()
f.seek(0)
f.write('0,0,0,0\n')
f.write(orig)
f.write('1,1,1,1\n')
f.close()

In [107]:
!cat storing_data/matrix_2.txt

0,0,0,0
152,312,1004,578,42,158,528,970,367,783,704,783,288,215,913,873,914,745,282,928,607,745,265,269,981,174,84,688,694,904,567,824,487,736,825,485,188,139,541,523,600,208,449,752,382,665,962,922,184,890
738,802,444,1022,214,50,820,22,372,531,869,553,616,117,232,1004,549,366,497,448,319,206,912,73,304,816,173,295,739,947,980,635,814,768,980,471,943,720,386,715,976,828,776,962,42,6,583,904,373,561
156,115,463,551,810,132,83,418,170,736,319,651,205,321,243,643,856,994,724,230,983,592,598,12,1022,721,69,291,930,1009,853,977,819,362,914,741,607,801,995,942,428,226,717,484,492,551,37,151,438,730
657,148,444,25,731,648,295,890,965,48,758,2,625,682,859,448,427,744,1009,787,608,202,777,440,597,650,309,443,760,123,222,848,693,150,720,410,34,86,123,624,134,320,159,859,254,733,626,599,271,876
752,917,925,844,718,530,354,334,723,774,1000,777,438,465,344,377,196,211,159,341,895,425,999,312,251,456,721,140,100,995,447,551,542,518,394,578,442,265,296,552,67,54,1020,747,968,15,221,796,633,921
800,1

#### The `with` statement (context manager)

In [109]:
matrix = []
with open('storing_data/matrix.txt') as f:
    for line in f.readlines():
        row = [int(x) for x in line.split(',')]
        matrix.append(row)
A = np.array(matrix, dtype='uint16')
A

array([[ 152,  312, 1004, ...,  922,  184,  890],
       [ 738,  802,  444, ...,  904,  373,  561],
       [ 156,  115,  463, ...,  151,  438,  730],
       ...,
       [ 884,  712,  923, ...,  988,  387,  136],
       [ 610,  967,  917, ...,  227,  383,  482],
       [ 295,  901,  355, ...,  999,  220,  726]], dtype=uint16)

**This will automatically close the file when leaving the `with` block**

NumPy has the ability to save arrays as text files

In [132]:
np.savetxt('storing_data/matrix_3.txt', A)
np.savetxt('storing_data/matrix_4.txt', A, fmt='%d')

In [133]:
!head -1 storing_data/matrix_3.txt

1.520000000000000000e+02 3.120000000000000000e+02 1.004000000000000000e+03 5.780000000000000000e+02 4.200000000000000000e+01 1.580000000000000000e+02 5.280000000000000000e+02 9.700000000000000000e+02 3.670000000000000000e+02 7.830000000000000000e+02 7.040000000000000000e+02 7.830000000000000000e+02 2.880000000000000000e+02 2.150000000000000000e+02 9.130000000000000000e+02 8.730000000000000000e+02 9.140000000000000000e+02 7.450000000000000000e+02 2.820000000000000000e+02 9.280000000000000000e+02 6.070000000000000000e+02 7.450000000000000000e+02 2.650000000000000000e+02 2.690000000000000000e+02 9.810000000000000000e+02 1.740000000000000000e+02 8.400000000000000000e+01 6.880000000000000000e+02 6.940000000000000000e+02 9.040000000000000000e+02 5.670000000000000000e+02 8.240000000000000000e+02 4.870000000000000000e+02 7.360000000000000000e+02 8.250000000000000000e+02 4.850000000000000000e+02 1.880000000000000000e+02 1.390000000000000000e+02 5.410000000000000000e+02 5.230000000000000000e+02 

In [134]:
!head -1 storing_data/matrix_4.txt

152 312 1004 578 42 158 528 970 367 783 704 783 288 215 913 873 914 745 282 928 607 745 265 269 981 174 84 688 694 904 567 824 487 736 825 485 188 139 541 523 600 208 449 752 382 665 962 922 184 890


and also as binary files:

In [141]:
np.save('storing_data/matrix_5.npy', A, )

In [144]:
np.savez('storing_data/matrix_6.npz', A, ) # compressed with gzip

In [145]:
!ls -l storing_data

total 416
-rw-r--r--  1 jmunroe  staff   5128 24 May 12:06 matrix.npy
-rw-r--r--  1 jmunroe  staff   9804 24 May 12:01 matrix.txt
-rw-r--r--  1 jmunroe  staff  62500 24 May 12:05 matrix3.txt
-rw-r--r--  1 jmunroe  staff   9804 24 May 12:05 matrix4.txt
-rw-r--r--  1 jmunroe  staff   9820 24 May 12:02 matrix_2.txt
-rw-r--r--  1 jmunroe  staff  62500 24 May 12:06 matrix_3.txt
-rw-r--r--  1 jmunroe  staff   9804 24 May 12:06 matrix_4.txt
-rw-r--r--  1 jmunroe  staff   5128 24 May 12:07 matrix_5.npy
-rw-r--r--  1 jmunroe  staff   5244 24 May 12:07 matrix_5.npz
-rw-r--r--  1 jmunroe  staff   5244 24 May 12:07 matrix_6.npz


## HDF5 files (Hierachrical Data Format)

The package PyTables is used in this section.

* PyTables User Guide: <http://www.pytables.org/usersguide/>

In [213]:
import os
import numpy as np
if os.path.isfile('ch10.h5'):
    os.remove('ch10.h5')

In [214]:
import tables as tb
f = tb.open_file('ch10.h5', 'a')

( If the above import command failed, you need to install PyTables first.
If you are using conda, the required command is `conda install pytables` )

Create a group on the root node with the name `a_group` with the title "My Group" :

In [215]:
f.create_group('/', 'a_group', "My Group")
f.root.a_group

/a_group (Group) 'My Group'
  children := []

In PyTables, arrays are of fixed size. They have to be created with data.
Tables need to have the same datetype (like in NumPy) and have variable length.

In [216]:
# integer array
f.create_array('/a_group', 'arthur_count', np.array([1, 2, 5, 3]))

# tables need descriptions
dt = np.dtype([('id', int), ('name', 'S10')])
knights = np.array([(42, 'Lancelot'), (12, 'Bedivere')], dtype=dt)
f.create_table('/', 'knights', dt)
f.root.knights.append(knights)

The hierarchy now looks like:

```
/
|-- a_group/
|   |-- arthur_count
|
|-- knights
```

In [217]:
f.root.a_group.arthur_count[:]

array([1, 2, 5, 3])

In [218]:
type(f.root.a_group.arthur_count[:])

numpy.ndarray

In [219]:
type(f.root.a_group.arthur_count)

tables.array.Array

In [220]:
f.root.knights[1]

(12, b'Bedivere')

In [221]:
f.root.knights[:1] 

array([(42, b'Lancelot')], dtype=[('id', '<i8'), ('name', 'S10')])

In [222]:
mask = (f.root.knights.cols.id[:] < 28)
f.root.knights[mask]

array([(12, b'Bedivere')], dtype=[('id', '<i8'), ('name', 'S10')])

In [223]:
f.root.knights[([1, 0],)]

array([(12, b'Bedivere'), (42, b'Lancelot')],
      dtype=[('id', '<i8'), ('name', 'S10')])

In [224]:
# don't forget to close the file
f.close()

## Hierachry Layout

##  In-Core and Out-of-Core operations

### In-Core operations

```python
a = np.array(...)
b = np.array(...)
c = 42 * a + 28 * b + 6
```

is equivalent to :

```python
temp1 = 42 * a
temp2 = 28 * b
temp3 = temp1 + temp2
c = temp3 + 6
```
This can exhaust memory if the arrays are very large.

Alternatively it could be implemented element-wise as:

```python
c = np.empty(...)
for i in range(len(c)):
    c[i] = 42 * a[i] + 28 * b[i] + 6
```

This version needs less memory, but can be extremely slow if each dataset needs to be read from disk one by one.


### Out-of-Core operations

A better strategy is to use a hybrid, loading reasonable sized chunks of several elements into memory an performing the operations on all elements in the chunk, before processing the next chunk.

In Python the `numexpr` library provides a way to perform chunked, element-wise computations on NumPy arrays.  PyTables offers the `tb.Expr` class to do just that.

In [225]:
# clean-up
if os.path.isfile('ch10-1.h5'):
    os.remove('ch10-1.h5')

# open a new file
shape = (10, 10000)
f = tb.open_file('ch10-1.h5', "w")

# create the arrays 
a = f.create_carray(f.root, 'a', tb.Float32Atom(dflt=1.), shape)
b = f.create_carray(f.root, 'b', tb.Float32Atom(dflt=2.), shape)
c = f.create_carray(f.root, 'c', tb.Float32Atom(dflt=3.), shape)

In [236]:
f

File(filename=ch10-1.h5, title='', mode='w', root_uep='/', filters=Filters(complevel=0, shuffle=False, bitshuffle=False, fletcher32=False, least_significant_digit=None))
/ (RootGroup) ''
/a (CArray(10, 10000)) ''
  atom := Float32Atom(shape=(), dflt=1.0)
  maindim := 0
  flavor := 'numpy'
  byteorder := 'little'
  chunkshape := (1, 10000)
/b (CArray(10, 10000)) ''
  atom := Float32Atom(shape=(), dflt=2.0)
  maindim := 0
  flavor := 'numpy'
  byteorder := 'little'
  chunkshape := (1, 10000)
/c (CArray(10, 10000)) ''
  atom := Float32Atom(shape=(), dflt=3.0)
  maindim := 0
  flavor := 'numpy'
  byteorder := 'little'
  chunkshape := (1, 10000)

In [237]:
# evaluate the expression, using the c array as the output
expr = tb.Expr("42*a + 28*b + 6")
expr.set_output(c)
expr.eval()

/c (CArray(10, 10000)) ''
  atom := Float32Atom(shape=(), dflt=3.0)
  maindim := 0
  flavor := 'numpy'
  byteorder := 'little'
  chunkshape := (1, 10000)

In [30]:
# close the file
f.close()

## Querying



```python
for row in tab.where('(col1 < 42) and col2 == col3'):
    #do something with row
```


In [243]:
# prepare some random data
n = 1000
data = np.random.randint(0, 100, size=(n, 3))

# and create some hits for our query
for i in np.random.randint(0, n, n//20):
    data[i,2] = data[i,1]

In [244]:
# cleanup:
if os.path.exists('ch10-3.h5'):
    os.remove('ch10-3.h5')

# Datatype / table headers
dt = np.dtype([
        ('col1', int),
        ('col2', int),
        ('col3', int),
])

# create a table all_data in a file:
f = tb.open_file('ch10-3.h5', 'a')
tab = f.create_table('/', 'all_data', dt)
tab.append(data)

**`tb.Table.where(condition)`** returns an iterator of matches:

In [247]:
for row in tab.where('(col1 < 42) & (col2 == col3)'):
    # do something with data in row
    print (row[:])

(35, 9, 9)
(4, 79, 79)
(23, 29, 29)
(35, 13, 13)
(1, 62, 62)
(22, 4, 4)
(0, 10, 10)
(0, 98, 98)
(27, 86, 86)
(38, 38, 38)
(16, 10, 10)
(6, 44, 44)
(26, 35, 35)
(15, 19, 19)
(20, 34, 34)
(14, 92, 92)
(13, 62, 62)
(38, 81, 81)
(3, 41, 41)
(1, 96, 96)
(38, 31, 31)
(3, 50, 50)


**`tb.Table.get_where_list(condition)`** returns a list of indices:

In [248]:
# get list of indices
tab.get_where_list('(col1 < 42) & (col2 == col3)')

array([  2,  18,  48,  67, 159, 193, 251, 341, 375, 393, 416, 469, 515,
       572, 589, 632, 654, 693, 772, 832, 849, 903])

**`tb.Table.read_where(condition)`** returns a list of results:

In [249]:
tab.read_where('(col1 < 42) & (col2 == col3)')

array([(35,  9,  9), ( 4, 79, 79), (23, 29, 29), (35, 13, 13),
       ( 1, 62, 62), (22,  4,  4), ( 0, 10, 10), ( 0, 98, 98),
       (27, 86, 86), (38, 38, 38), (16, 10, 10), ( 6, 44, 44),
       (26, 35, 35), (15, 19, 19), (20, 34, 34), (14, 92, 92),
       (13, 62, 62), (38, 81, 81), ( 3, 41, 41), ( 1, 96, 96),
       (38, 31, 31), ( 3, 50, 50)],
      dtype=[('col1', '<i8'), ('col2', '<i8'), ('col3', '<i8')])

**`tb.Table.append_where(destination, condition)`** appends results to a different table:

In [250]:
tab2 = f.create_table('/', 'some_data', dt)
tab.append_where(tab2 , '(col1 < 42) & (col2 == col3)')

22

In [253]:
# close the file
f.close()

## HDF5 utilities

**h5ls** - list content of HDF5 files:

In [254]:
!h5ls ch10-3.h5

all_data                 Dataset {1000/Inf}
some_data                Dataset {22/Inf}


**h5dump** - print content of an HDF5 table:

In [255]:
!h5dump -d "/some_data" ch10-3.h5

HDF5 "ch10-3.h5" {
DATASET "/some_data" {
   DATATYPE  H5T_COMPOUND {
      H5T_STD_I64LE "col1";
      H5T_STD_I64LE "col2";
      H5T_STD_I64LE "col3";
   }
   DATASPACE  SIMPLE { ( 22 ) / ( H5S_UNLIMITED ) }
   DATA {
   (0): {
         35,
         9,
         9
      },
   (1): {
         4,
         79,
         79
      },
   (2): {
         23,
         29,
         29
      },
   (3): {
         35,
         13,
         13
      },
   (4): {
         1,
         62,
         62
      },
   (5): {
         22,
         4,
         4
      },
   (6): {
         0,
         10,
         10
      },
   (7): {
         0,
         98,
         98
      },
   (8): {
         27,
         86,
         86
      },
   (9): {
         38,
         38,
         38
      },
   (10): {
         16,
         10,
         10
      },
   (11): {
         6,
         44,
         44
      },
   (12): {
         26,
         35,
         35
      },
   (13): {
         15,
         19,
       